const paintingsList = [' ./static/img/paintings/IMG_4502.jpg', 
'./static/img/paintings/IMG_5108.jpg',
'./static/img/paintings/IMG_5124.jpg',
'./static/img/paintings/IMG_5139.jpg',
'./static/img/paintings/IMG_5143.jpg',
'./static/img/paintings/IMG_5228.jpg',
'./static/img/paintings/IMG_5229.jpg',
'./static/img/paintings/IMG_5235.jpg',
'./static/img/paintings/IMG_6452.jpg',
'./static/img/paintings/IMG_6543.jpg',
'./static/img/paintings/IMG_6548.jpg',
'./static/img/paintings/IMG_6555.jpg',
'./static/img/paintings/IMG_6558.jpg',
'./static/img/paintings/IMG_6562.jpg',
'./static/img/paintings/IMG_6563.jpg',
'./static/img/paintings/IMG_7110.jpg',
'./static/img/paintings/IMG_7154_2.jpg',
'./static/img/paintings/IMG_7166_q2.jpg',
'./static/img/paintings/IMG_7204.jpg',
'./static/img/paintings/IMG_7211.jpg',
'./static/img/paintings/IMG_7233.jpg',
'./static/img/paintings/IMG_7239.jpg',
'./static/img/paintings/IMG_7245.jpg',
'./static/img/paintings/IMG_7249.jpg',
'./static/img/paintings/IMG_7273.jpg',
'./static/img/paintings/IMG_7293.jpg',
'./static/img/paintings/IMG_7298.jpg',
'./static/img/paintings/IMG_7304.jpg',
'./static/img/paintings/IMG_72391.jpg',
];

const drawingsList = [];

const photosList = [];
